import { createContext, useContext, useState, useEffect } from "react";

export const LANGUAGES = {
  en: { label: "EN", name: "English", dir: "ltr" },
  ar: { label: "ع", name: "العربية", dir: "rtl" },
  fr: { label: "FR", name: "Français", dir: "ltr" },
  es: { label: "ES", name: "Español", dir: "ltr" },
};

export const T = {
  en: {
    // TopBar
    appSubtitle: "Global Conflict Intelligence",
    live: "LIVE",
    activeEvents: "Active Events:",
    aiRealtime: "AI REAL-TIME",
    logEvent: "Log Event",
    // Map
    initializingRadar: "Initializing Radar...",
    poweredByAI: "Powered by AI",
    // PulseFeed
    pulseFeed: "Pulse Feed",
    searchEvents: "Search events...",
    noEventsFound: "No events found",
    filterAll: "ALL",
    filterHigh: "HIGH",
    filterMed: "MED",
    filterLow: "LOW",
    filterEsc: "ESC",
    // SmartDigest
    smartDigest: "Smart Digest",
    generate: "Generate",
    refresh: "Refresh",
    analyzing: (n) => `Analyzing ${n} conflict events...`,
    generatingAssessments: "Generating impact assessments & recommendations...",
    clickGenerate: "Click Generate to get an AI-powered intelligence digest with impact assessments and recommended actions.",
    threat: "THREAT:",
    eventBriefings: "Event Briefings",
    // Correlation
    correlations: "Correlations",
    clickRefreshCorrelation: "Click refresh to run AI\ncorrelation analysis",
    lastAnalyzed: "Last analyzed",
    risk: "Risk:",
    events: "events",
    // TrendAnalysis
    trendAnalysis: "Trend Analysis",
    aiInsights: "AI Insights",
    total: "Total",
    highSev: "High Sev",
    escalations: "Escalations",
    dayActivity: "14-Day Activity",
    regionHeatmap: "Region Heatmap — Past 6 Months",
    eventTypeTrends: "Event Type Trends — 4 Weeks",
    topHotspots: "Top Hotspots",
    aiPredictiveInsights: "AI Predictive Insights",
    analyzingPatterns: "Analyzing patterns...",
    generateAIPredictions: "✨ Generate AI Predictions",
    low: "Low",
    high: "High",
    // NewsFeed
    newsFeed: "News Feed",
    checking: "checking",
    submit: "Submit",
    loadingNews: "Loading news...",
    noNewsYet: "No news submitted yet. Be the first!",
    submitNewsReport: "Submit News Report",
    headline: "Headline *",
    describeNews: "Describe the news in detail... *",
    sourceUrl: "Source URL (optional)",
    authorName: "Your name (optional)",
    regionCountry: "Region / Country (optional)",
    submitting: "Submitting...",
    submitVerify: "Submit & Verify",
    cancel: "Cancel",
    showLess: "Show less",
    readMore: "Read more",
    source: "Source",
    anonymous: "Anonymous",
    aiFact: "AI Fact-Check",
    // EventDetail
    summary: "Summary",
    aiAnalysis: "AI Analysis",
    tags: "Tags",
    escalation: "ESCALATION",
    confidence: (n) => `${n}% confidence`,
    // AddEventModal
    logNewEvent: "Log New Event",
    eventTitle: "Event Title *",
    describeIncident: "Describe the incident...",
    severity: "Severity",
    eventType: "Event Type",
    country: "Country",
    selectCountry: "Select...",
    confidencePct: "Confidence %",
    regionLocation: "Region / Location",
    regionPlaceholder: "e.g. Southern Beirut, Northern Gaza",
    summaryLabel: "Summary",
    summaryPlaceholder: "Brief description of the event...",
    markEscalation: "Mark as Escalation",
    saving: "Saving...",
    logEventBtn: "Log Event",
    // Status labels
    statusChecking: "Checking...",
    statusVerified: "AI Verified",
    statusUnverified: "Unverified",
    statusFalse: "False Info",
    // Event type labels
    typeAirstrike: "Airstrike",
    typeMissile: "Missile Attack",
    typeExplosion: "Explosion",
    typeClash: "Armed Clash",
    typeThreat: "Threat",
    typeDiplomatic: "Diplomatic",
    typeCyberattack: "Cyberattack",
    typeNaval: "Naval Incident",
    typeOther: "Incident",
  },
  ar: {
    appSubtitle: "استخبارات النزاعات العالمية",
    live: "مباشر",
    activeEvents: "الأحداث النشطة:",
    aiRealtime: "ذكاء اصطناعي فوري",
    logEvent: "تسجيل حدث",
    initializingRadar: "جارٍ تهيئة الرادار...",
    poweredByAI: "مدعوم بالذكاء الاصطناعي",
    pulseFeed: "التغذية المباشرة",
    searchEvents: "البحث في الأحداث...",
    noEventsFound: "لا توجد أحداث",
    filterAll: "الكل",
    filterHigh: "عالٍ",
    filterMed: "متوسط",
    filterLow: "منخفض",
    filterEsc: "تصعيد",
    smartDigest: "الملخص الذكي",
    generate: "توليد",
    refresh: "تحديث",
    analyzing: (n) => `تحليل ${n} حدث نزاع...`,
    generatingAssessments: "جارٍ توليد تقييمات التأثير والتوصيات...",
    clickGenerate: "انقر على توليد للحصول على ملخص استخباراتي مدعوم بالذكاء الاصطناعي.",
    threat: "مستوى التهديد:",
    eventBriefings: "إحاطات الأحداث",
    correlations: "الترابطات",
    clickRefreshCorrelation: "انقر تحديث لتشغيل\nتحليل الترابط بالذكاء الاصطناعي",
    lastAnalyzed: "آخر تحليل",
    risk: "الخطر:",
    events: "أحداث",
    trendAnalysis: "تحليل الاتجاهات",
    aiInsights: "رؤى الذكاء الاصطناعي",
    total: "الإجمالي",
    highSev: "خطورة عالية",
    escalations: "التصعيدات",
    dayActivity: "نشاط 14 يوم",
    regionHeatmap: "خريطة الحرارة الإقليمية — 6 أشهر",
    eventTypeTrends: "اتجاهات أنواع الأحداث — 4 أسابيع",
    topHotspots: "أبرز البؤر",
    aiPredictiveInsights: "رؤى الذكاء الاصطناعي التنبؤية",
    analyzingPatterns: "تحليل الأنماط...",
    generateAIPredictions: "✨ توليد تنبؤات الذكاء الاصطناعي",
    low: "منخفض",
    high: "عالٍ",
    newsFeed: "خلاصة الأخبار",
    checking: "جارٍ الفحص",
    submit: "إرسال",
    loadingNews: "تحميل الأخبار...",
    noNewsYet: "لا أخبار بعد. كن الأول!",
    submitNewsReport: "إرسال تقرير إخباري",
    headline: "العنوان *",
    describeNews: "وصف الخبر بالتفصيل... *",
    sourceUrl: "رابط المصدر (اختياري)",
    authorName: "اسمك (اختياري)",
    regionCountry: "المنطقة / الدولة (اختياري)",
    submitting: "جارٍ الإرسال...",
    submitVerify: "إرسال والتحقق",
    cancel: "إلغاء",
    showLess: "عرض أقل",
    readMore: "اقرأ المزيد",
    source: "المصدر",
    anonymous: "مجهول",
    aiFact: "فحص الحقائق بالذكاء الاصطناعي",
    summary: "الملخص",
    aiAnalysis: "تحليل الذكاء الاصطناعي",
    tags: "الوسوم",
    escalation: "تصعيد",
    confidence: (n) => `ثقة ${n}%`,
    logNewEvent: "تسجيل حدث جديد",
    eventTitle: "عنوان الحدث *",
    describeIncident: "وصف الحادثة...",
    severity: "الخطورة",
    eventType: "نوع الحدث",
    country: "الدولة",
    selectCountry: "اختر...",
    confidencePct: "نسبة الثقة %",
    regionLocation: "المنطقة / الموقع",
    regionPlaceholder: "مثال: جنوب بيروت، شمال غزة",
    summaryLabel: "الملخص",
    summaryPlaceholder: "وصف مختصر للحدث...",
    markEscalation: "تحديد كتصعيد",
    saving: "جارٍ الحفظ...",
    logEventBtn: "تسجيل الحدث",
  },
  fr: {
    appSubtitle: "Renseignement sur les conflits mondiaux",
    live: "EN DIRECT",
    activeEvents: "Événements actifs :",
    aiRealtime: "IA EN TEMPS RÉEL",
    logEvent: "Enregistrer",
    initializingRadar: "Initialisation du radar...",
    poweredByAI: "Propulsé par l'IA",
    pulseFeed: "Flux en direct",
    searchEvents: "Rechercher des événements...",
    noEventsFound: "Aucun événement trouvé",
    filterAll: "TOUS",
    filterHigh: "ÉLEVÉ",
    filterMed: "MOY",
    filterLow: "FAIBLE",
    filterEsc: "ESC",
    smartDigest: "Digest Intelligent",
    generate: "Générer",
    refresh: "Actualiser",
    analyzing: (n) => `Analyse de ${n} événements...`,
    generatingAssessments: "Génération des évaluations et recommandations...",
    clickGenerate: "Cliquez sur Générer pour obtenir un digest de renseignement propulsé par l'IA.",
    threat: "MENACE :",
    eventBriefings: "Briefings d'événements",
    correlations: "Corrélations",
    clickRefreshCorrelation: "Cliquez actualiser pour lancer\nl'analyse de corrélation IA",
    lastAnalyzed: "Dernière analyse",
    risk: "Risque :",
    events: "événements",
    trendAnalysis: "Analyse des tendances",
    aiInsights: "Insights IA",
    total: "Total",
    highSev: "Sévérité haute",
    escalations: "Escalades",
    dayActivity: "Activité 14 jours",
    regionHeatmap: "Carte thermique — 6 derniers mois",
    eventTypeTrends: "Tendances par type — 4 semaines",
    topHotspots: "Principaux points chauds",
    aiPredictiveInsights: "Insights prédictifs IA",
    analyzingPatterns: "Analyse des modèles...",
    generateAIPredictions: "✨ Générer des prédictions IA",
    low: "Faible",
    high: "Élevé",
    newsFeed: "Flux d'actualités",
    checking: "en vérification",
    submit: "Soumettre",
    loadingNews: "Chargement des actualités...",
    noNewsYet: "Aucune actualité soumise. Soyez le premier !",
    submitNewsReport: "Soumettre un rapport",
    headline: "Titre *",
    describeNews: "Décrivez l'actualité en détail... *",
    sourceUrl: "URL de la source (optionnel)",
    authorName: "Votre nom (optionnel)",
    regionCountry: "Région / Pays (optionnel)",
    submitting: "Envoi en cours...",
    submitVerify: "Soumettre et vérifier",
    cancel: "Annuler",
    showLess: "Voir moins",
    readMore: "Lire plus",
    source: "Source",
    anonymous: "Anonyme",
    aiFact: "Vérification IA",
    summary: "Résumé",
    aiAnalysis: "Analyse IA",
    tags: "Étiquettes",
    escalation: "ESCALADE",
    confidence: (n) => `${n}% de confiance`,
    logNewEvent: "Enregistrer un événement",
    eventTitle: "Titre de l'événement *",
    describeIncident: "Décrivez l'incident...",
    severity: "Sévérité",
    eventType: "Type d'événement",
    country: "Pays",
    selectCountry: "Choisir...",
    confidencePct: "Confiance %",
    regionLocation: "Région / Lieu",
    regionPlaceholder: "ex. Sud de Beyrouth, Nord de Gaza",
    summaryLabel: "Résumé",
    summaryPlaceholder: "Brève description de l'événement...",
    markEscalation: "Marquer comme escalade",
    saving: "Enregistrement...",
    logEventBtn: "Enregistrer l'événement",
  },
  es: {
    appSubtitle: "Inteligencia de conflictos globales",
    live: "EN VIVO",
    activeEvents: "Eventos activos:",
    aiRealtime: "IA EN TIEMPO REAL",
    logEvent: "Registrar",
    initializingRadar: "Iniciando radar...",
    poweredByAI: "Impulsado por IA",
    pulseFeed: "Feed en vivo",
    searchEvents: "Buscar eventos...",
    noEventsFound: "No se encontraron eventos",
    filterAll: "TODOS",
    filterHigh: "ALTO",
    filterMed: "MED",
    filterLow: "BAJO",
    filterEsc: "ESC",
    smartDigest: "Resumen Inteligente",
    generate: "Generar",
    refresh: "Actualizar",
    analyzing: (n) => `Analizando ${n} eventos de conflicto...`,
    generatingAssessments: "Generando evaluaciones de impacto y recomendaciones...",
    clickGenerate: "Haga clic en Generar para obtener un resumen de inteligencia impulsado por IA.",
    threat: "AMENAZA:",
    eventBriefings: "Informes de eventos",
    correlations: "Correlaciones",
    clickRefreshCorrelation: "Haga clic en actualizar para ejecutar\nel análisis de correlación IA",
    lastAnalyzed: "Último análisis",
    risk: "Riesgo:",
    events: "eventos",
    trendAnalysis: "Análisis de tendencias",
    aiInsights: "Perspectivas IA",
    total: "Total",
    highSev: "Alta severidad",
    escalations: "Escaladas",
    dayActivity: "Actividad 14 días",
    regionHeatmap: "Mapa de calor regional — 6 meses",
    eventTypeTrends: "Tendencias por tipo — 4 semanas",
    topHotspots: "Principales puntos calientes",
    aiPredictiveInsights: "Perspectivas predictivas IA",
    analyzingPatterns: "Analizando patrones...",
    generateAIPredictions: "✨ Generar predicciones IA",
    low: "Bajo",
    high: "Alto",
    newsFeed: "Feed de noticias",
    checking: "verificando",
    submit: "Enviar",
    loadingNews: "Cargando noticias...",
    noNewsYet: "Ninguna noticia enviada aún. ¡Sé el primero!",
    submitNewsReport: "Enviar reporte de noticias",
    headline: "Titular *",
    describeNews: "Describe la noticia en detalle... *",
    sourceUrl: "URL de la fuente (opcional)",
    authorName: "Tu nombre (opcional)",
    regionCountry: "Región / País (opcional)",
    submitting: "Enviando...",
    submitVerify: "Enviar y verificar",
    cancel: "Cancelar",
    showLess: "Ver menos",
    readMore: "Leer más",
    source: "Fuente",
    anonymous: "Anónimo",
    aiFact: "Verificación IA",
    summary: "Resumen",
    aiAnalysis: "Análisis IA",
    tags: "Etiquetas",
    escalation: "ESCALADA",
    confidence: (n) => `${n}% confianza`,
    logNewEvent: "Registrar nuevo evento",
    eventTitle: "Título del evento *",
    describeIncident: "Describe el incidente...",
    severity: "Severidad",
    eventType: "Tipo de evento",
    country: "País",
    selectCountry: "Seleccionar...",
    confidencePct: "Confianza %",
    regionLocation: "Región / Ubicación",
    regionPlaceholder: "ej. Sur de Beirut, Norte de Gaza",
    summaryLabel: "Resumen",
    summaryPlaceholder: "Breve descripción del evento...",
    markEscalation: "Marcar como escalada",
    saving: "Guardando...",
    logEventBtn: "Registrar evento",
  },
};

const LanguageContext = createContext({ lang: "en", setLang: () => {}, t: T.en });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("lbc_lang") || "en"
  );

  useEffect(() => {
    document.documentElement.dir = LANGUAGES[lang]?.dir || "ltr";
  }, [lang]);

  const handleSetLang = (l) => {
    setLang(l);
    localStorage.setItem("lbc_lang", l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: T[lang] || T.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}